// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEnxzVN78msCVCH-lEMqP37yBQr0BvylQ',
    appId: '1:736785257639:web:c0da6b1d982121241cb782',
    messagingSenderId: '736785257639',
    projectId: 'jong-user-authentication',
    authDomain: 'jong-user-authentication.firebaseapp.com',
    storageBucket: 'jong-user-authentication.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV22s6MBQ-8lfrxDJxS8I20sWlgwK-Isw',
    appId: '1:736785257639:android:b6f2075798b01e8a1cb782',
    messagingSenderId: '736785257639',
    projectId: 'jong-user-authentication',
    storageBucket: 'jong-user-authentication.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRRwWUVp9rcPTurwasxEByhenVAZeJ-Dg',
    appId: '1:736785257639:ios:190cbfe4473218df1cb782',
    messagingSenderId: '736785257639',
    projectId: 'jong-user-authentication',
    storageBucket: 'jong-user-authentication.firebasestorage.app',
    iosBundleId: 'com.example.notificationFcmToken',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRRwWUVp9rcPTurwasxEByhenVAZeJ-Dg',
    appId: '1:736785257639:ios:190cbfe4473218df1cb782',
    messagingSenderId: '736785257639',
    projectId: 'jong-user-authentication',
    storageBucket: 'jong-user-authentication.firebasestorage.app',
    iosBundleId: 'com.example.notificationFcmToken',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEnxzVN78msCVCH-lEMqP37yBQr0BvylQ',
    appId: '1:736785257639:web:3cca4d4c683cd0661cb782',
    messagingSenderId: '736785257639',
    projectId: 'jong-user-authentication',
    authDomain: 'jong-user-authentication.firebaseapp.com',
    storageBucket: 'jong-user-authentication.firebasestorage.app',
  );

}