// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB31ZJoGPl7UWlTgtcFJ4MtRY5y8PSHl2Y',
    appId: '1:906015471708:web:a1e33f9ae72e2180ef8e99',
    messagingSenderId: '906015471708',
    projectId: 'jong-notification-local-adb77',
    authDomain: 'jong-notification-local-adb77.firebaseapp.com',
    storageBucket: 'jong-notification-local-adb77.firebasestorage.app',
    measurementId: 'G-G5CW4TQ984',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWq64CE2NLmcSny5euy_hMUtNPXbZRkGM',
    appId: '1:906015471708:android:631b4f6a968909b5ef8e99',
    messagingSenderId: '906015471708',
    projectId: 'jong-notification-local-adb77',
    storageBucket: 'jong-notification-local-adb77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdrJjn2cSS3iajGrt-o9dPCtFDIpgOZ5Q',
    appId: '1:906015471708:ios:7ed11dc2b9832a46ef8e99',
    messagingSenderId: '906015471708',
    projectId: 'jong-notification-local-adb77',
    storageBucket: 'jong-notification-local-adb77.firebasestorage.app',
    iosBundleId: 'com.example.notificationFcmToken',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdrJjn2cSS3iajGrt-o9dPCtFDIpgOZ5Q',
    appId: '1:906015471708:ios:7ed11dc2b9832a46ef8e99',
    messagingSenderId: '906015471708',
    projectId: 'jong-notification-local-adb77',
    storageBucket: 'jong-notification-local-adb77.firebasestorage.app',
    iosBundleId: 'com.example.notificationFcmToken',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB31ZJoGPl7UWlTgtcFJ4MtRY5y8PSHl2Y',
    appId: '1:906015471708:web:a4dfc682dc7b3da5ef8e99',
    messagingSenderId: '906015471708',
    projectId: 'jong-notification-local-adb77',
    authDomain: 'jong-notification-local-adb77.firebaseapp.com',
    storageBucket: 'jong-notification-local-adb77.firebasestorage.app',
    measurementId: 'G-N7E3FEZXGQ',
  );
}
